/**
 * Content seeding script — generated by SiteProof.
 *
 * Run after Payload is initialized to populate initial content
 * from the values found in the source code.
 */

import { getPayload } from 'payload';
import config from './payload.config';

async function seed() {
  const payload = await getPayload({ config });

  await payload.create({
    collection: 'layout',
    data: {
      title: '(content from app/layout.tsx:10)',
      description: '(content from app/layout.tsx:11)',
      opengraphtitle: '(content from app/layout.tsx:13)',
      opengraphdescription: '(content from app/layout.tsx:14)',
      twittertitle: '(content from app/layout.tsx:19)',
      twitterdescription: '(content from app/layout.tsx:20)',
    },
  });

  await payload.create({
    collection: 'logo',
    data: {
      arialabel: '(content from components/logo.tsx:15)',
      companyname: '(content from components/logo.tsx:43)',
      companynameaccent: '(content from components/logo.tsx:44)',
    },
  });

  await payload.create({
    collection: 'home',
    data: {
      comingsoontext: '(content from app/page.tsx:49)',
      headline: '(content from app/page.tsx:59)',
      subheadline: '(content from app/page.tsx:65)',
      ctatext: '(content from app/page.tsx:91)',
      disclaimer: '(content from app/page.tsx:103)',
      sectiontitle: '(content from app/page.tsx:115)',
      sectionsubtitle: '(content from app/page.tsx:118)',
      title: '(content from app/page.tsx:129)',
      description: '(content from app/page.tsx:130)',
      title: '(content from app/page.tsx:139)',
      description: '(content from app/page.tsx:140)',
      title: '(content from app/page.tsx:149)',
      description: '(content from app/page.tsx:150)',
    },
  });

  console.log('Content seeded successfully.');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
